# Generated by Django 4.2.11 on 2024-03-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_booking',
            name='seats',
        ),
        migrations.AddField(
            model_name='table_booking',
            name='table',
            field=models.CharField(choices=[('Table 1 (2 seats)', 'Table 1 (2 seats)'), ('Table 2 (2 seats)', 'Table 2 (2 seats)'), ('Table 3 (2 seats)', 'Table 3 (2 seats)'), ('Table 4 (4 seats)', 'Table 4 (4 seats)'), ('Table 5 (4 seats)', 'Table 5 (4 seats)'), ('Table 6 (4 seats)', 'Table 6 (4 seats)'), ('Table 7 (8 seats)', 'Table 7 (8 seats)'), ('Table 8 (8 seats)', 'Table 8 (8 seats)')], default='Table 1 (2 seats)', max_length=50),
        ),
    ]
